apiVersion: v1
kind: Secret
metadata:
  name: mongodb-secret
type: Opaque
data: 
  mongo-root-username: dXNlcm5hbWU=
  mongo-root-password: cGFzc3dvcmQ=

# We need to create the secret first, 
# so that the deployment doesn't refer 
# to a secret that doesn't exist yet